name: Keystone Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Secrets
        uses: wearedevx/keystone-action@main
        id: load_secrets
        with:
          keystone_slot_1: ${{ secrets.KEYSTONE_PROD_SLOT_1 }}
          keystone_slot_2: ${{ secrets.KEYSTONE_PROD_SLOT_2 }}
          keystone_slot_3: ${{ secrets.KEYSTONE_PROD_SLOT_3 }}
          keystone_slot_4: ${{ secrets.KEYSTONE_PROD_SLOT_4 }}
          keystone_slot_5: ${{ secrets.KEYSTONE_PROD_SLOT_5 }}

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: auth-proxy
          runtime: nodejs14
          entry_point: redirect
          env_vars: API_DOMAIN=${{ env.API_DOMAIN }}
          project_id: ${{ env.GCP_PROJECT }}
          region: ${{ env.GCP_REGION }}
          credentials: ${{ env.GCP_SA_KEY }}
